name: Build QPG

on:
  workflow_call:
    inputs:
      gameName:
        required: true
        type: string
      useTPBundling:
        required: false
        type: boolean
    secrets:
      NPM_TOKEN:
        required: true

jobs:
  checkout:
    runs-on: ubuntu-latest
    env:
      WORKING_PATH: /home/runner/work
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 25
      - uses: actions/upload-artifact@v4
        with:
          name: ${{ inputs.gameName }}
          path: ${{ github.workspace }}
          overwrite: true
  build-atlas:
    runs-on: ubuntu-latest
    needs: [checkout]
    env:
      WORKING_PATH: /home/runner/work
    steps:
      - uses: actions/setup-node@v4
        with:
          node-version: 25
      - uses: actions/download-artifact@v4
        if: ${{ inputs.useTPBundling != '' }}
        with:
          name: ${{ inputs.gameName }}
          path: ${{ github.workspace }}/

      - name: Install TP and dependencies
        if: ${{ inputs.useTPBundling != '' }}
        run: |
          sudo apt-get update
          curl --output /tmp/tp.deb https://www.codeandweb.com/download/texturepacker/7.0.3/TexturePacker-7.0.3.deb
          sudo apt-get -y install libegl1-mesa libgl1-mesa-glx libfontconfig libx11-6 libxkbcommon-x11-0 /tmp/tp.deb
          echo agree | TexturePacker --version
          TexturePacker --activate-license ${QPG_CONFIG_QPG_TEXTURE_PACKER_KEY} ${{ github.workspace }}/raw_assets/*.tps

      - uses: actions/upload-artifact@v4
        if: ${{ inputs.useTPBundling != '' }}
        with:
          name: ${{ inputs.gameName }}
          path: ${{ github.workspace }}
          overwrite: true
  build-project:
    runs-on: ubuntu-latest
    needs: [checkout, build-atlas]
    steps:
      - uses: actions/download-artifact@v4
        id: download
        with:
          name: ${{ inputs.gameName }}
          path: ${{ github.workspace }}

      - uses: actions/setup-node@v4
        with:
          node-version: 25
          registry-url: "https://registry.npmjs.org"
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}

      - name: Install dependencies
        working-directory: ${{ steps.download.outputs.download-path }}
        run: npm ci

      - name: Build
        working-directory: ${{ steps.download.outputs.download-path }}
        run: npm run build:dev

      - uses: actions/upload-artifact@v4
        with:
          name: ${{ inputs.gameName }}
          path: ${{ steps.download.outputs.download-path }}/dist
          overwrite: true
