name: deploy QPG to Coin Wizards and Golden Hearts Games

on:
  workflow_call:
    inputs:
      gameName:
        required: true
        type: string
      useTPBundling:
        required: true
        type: boolean
      deployTo:
        required: true
        type: string
    secrets:
      AWS_ACCESS_KEY_ID:
        required: true
      AWS_SECRET_ACCESS_KEY:
        required: true
      AWS_REGION:
        required: true
      SLACK_WEBHOOK:
        required: true
      NODE_AUTH_TOKEN:
        required: true

jobs:
  build:
    uses: goldenheartsgames/ci/.github/workflows/build-qpg.yml@coinwizards
    with:
      gameName: ${{ inputs.gameName }}
      useTPBundling: ${{ inputs.useTPBundling }}
    secrets:
      NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

  deployGHG:
    needs: build
    uses: goldenheartsgames/ci/.github/workflows/deploy-ghg.yml@coinwizards
    with:
      gameName: ${{ inputs.gameName }}
      deployTo: ${{ inputs.deployTo }}
    secrets:
      AWS_ACCESS_KEY_ID: ${{ secrets.DEV_AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.DEV_AWS_SECRET_ACCESS_KEY }}
      AWS_REGION: ${{ secrets.DEV_AWS_REGION }}
      SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}

  deployCW:
    needs: build
    uses: goldenheartsgames/ci/.github/workflows/deploy-cw.yml@coinwizards
    with:
      gameName: ${{ inputs.gameName }}
      deployTo: ${{ inputs.deployTo }}
    secrets:
      AWS_ACCESS_KEY_ID: ${{ secrets.DEV_AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.DEV_AWS_SECRET_ACCESS_KEY }}
      AWS_REGION: ${{ secrets.DEV_AWS_REGION }}
      SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}

  cleanup:
    runs-on: ubuntu-latest
    needs: [deployGHG, deployCW]
    steps:
      - uses: geekyeggo/delete-artifact@v4
        with:
          name: ${{ inputs.gameName }}
